server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
