INSERT INTO T_CUST_POINT (CUST_NO, GIVE_PNT_AMT, LEFT_PNT_AMT, EXT_DT) VALUES (891202, 1000, 1000, NOW() + 365);
INSERT INTO T_CUST_POINT (CUST_NO, GIVE_PNT_AMT, LEFT_PNT_AMT, EXT_DT) VALUES (891202, 2000, 2000, NOW() + 365);
INSERT INTO T_CUST_POINT (CUST_NO, GIVE_PNT_AMT, LEFT_PNT_AMT, EXT_DT) VALUES (891202, 3000, 3000, NOW() + 365);

INSERT INTO T_CUST_POINT_HST (CUST_POINT_IDX, GBN, HST_DESC, PNT_AMT, ORD_NO)
SELECT CUST_POINT_IDX
     , 'SAVE'
     , '포인트 적립'
     , GIVE_PNT_AMT
     , NULL
FROM   T_CUST_POINT
WHERE  1=1;

UPDATE T_CUST_POINT SET
USE_PNT_AMT = 1000,
LEFT_PNT_AMT = 0,
UPD_DT = NOW()
WHERE CUST_POINT_IDX = 1;

UPDATE T_CUST_POINT SET
USE_PNT_AMT = 1500,
LEFT_PNT_AMT = LEFT_PNT_AMT - 1500,
UPD_DT = NOW()
WHERE CUST_POINT_IDX = 2;

INSERT INTO T_CUST_POINT_HST (CUST_POINT_IDX, GBN, HST_DESC, PNT_AMT, ORD_NO) VALUES (1, 'USE', '주문사용', -1000, 891202);
INSERT INTO T_CUST_POINT_HST (CUST_POINT_IDX, GBN, HST_DESC, PNT_AMT, ORD_NO) VALUES (2, 'USE', '주문사용', -1500, 891202);